# Dependencies
markdown:         rdiscount
#redcarpet
highlighter:      pygments
gems:
  - jekyll-paginate

# Permalinks
#permalink:        pretty
permalink: "/:title"

# Setup
title:            Maxim Zaslavsky
tagline:          "Maxim Zaslavsky's blog: Some thoughts on science and technology, and updates on my work"
description:      "Updates from <a href='https://www.maximzaslavsky.com' rel='me' target='_blank'>Maxim Zaslavsky</a>."
url:              http://blog.maximzaslavsky.com
baseurl:          /

author:
  name:           'Maxim Zaslavsky'
  url:            https://www.maximzaslavsky.com

paginate:         5


# Custom vars go here


# See:
# http://joshualande.com/jekyll-github-pages-poole/
# http://joshualande.com/short-urls-jekyll/
# http://jekyllrb.com/docs/configuration/#front-matter-defaults