# Dependencies
markdown:         rdiscount
#redcarpet
highlighter:      rouge
gems:
  - jekyll-paginate

# Permalinks
#permalink:        pretty
permalink: "/:title"

# Setup
title:            Peter Griggs
tagline:          "Peter Griggs' Blog"
description:      "Programming, Security, Random Thoughts..."
url:              http://blog.petergriggs.com
baseurl:          /

#<a href='https://www.petergriggs.com' rel='me' target='_blank'>Peter Griggs</a>


author:
  name:           'Peter Griggs'
  url:            https://www.petergriggs.com

paginate:         5


# Custom vars go here


# See:
# http://joshualande.com/jekyll-github-pages-poole/
# http://joshualande.com/short-urls-jekyll/
# http://jekyllrb.com/docs/configuration/#front-matter-defaults
